### ISSUE TITLE
create open attestation renderer for commercial invoice

### ISSUE THREAD

**Issue by arpentnoir** [gs-gs/project-vckit#13]
- add new template to renderer here https://dev.azure.com/gosource-au/HA-DVP/_git/HA-DVP-Schema-Registry?path=/renderer/src/templates
- template can be based on this Invoice template https://github.com/TradeTrust/generic-templates/tree/master/src/templates/Invoice
- template should expect an open attestation document that has a credential subject structured 
  like the example commercial invoice here: https://w3c-ccg.github.io/traceability-vocab/#CommercialInvoiceCredential

**Comment by monkeypants** [comment]
based on the work we demoed last week @arpentnoir, I thik I saw this working on your laptop (right?). Is there anything left to do, once that stuff is checked in?
